### ISSUE TITLE
TODO all the things.

### ISSUE THREAD

**Issue by EvanCarroll** [EvanCarroll/browser_cookie#1]
Features I intend to implement.

- [ ] Complete Chrome Support (v1)
  - [x] Support pulling into Rust all data in Cookie table.
  - [ ] Support writing all data in Cookie table.

- [ ] Backup and Dump of Rust Structures
  - [ ] Serialize to JSON of Cookies
  - [ ] Deserialize from JSON (load from command line).

- [ ] Complete OS and Browser Support
  - [ ] Complete_ Linux Support (Debian) (v1)
    - [x] #2
    - [x] Support Chrome v10 as packaged in Debian.
    - [ ] #3
  - [ ] Complete OSX Support (v2)
    - [ ] Support Firefox
    - [ ] Support Chrome v10
    - [ ] Support Chrome v11
  - [ ] Complete Windows 10/12 Support (v3)
    - [ ] Support Firefox
    - [ ] #4
    - [ ] Support MS Edge

- [ ] Ideal test creation supports idempotent backup and delete of cookies.
  - Import to `browser_cookie`.
  - Delete from browser
  - Export from `browser_cookie`
